[package]
name = "nezuo/spark-preview"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml", "LICENSE"]
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
Midori = "nezuo/midori@0.1.3"
