[package]
name = "nezuo/spark"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
enumerate = "nezuo/enumerate@0.1.6"
Promise = "evaera/promise@4.0.0"
Subject = "nezuo/subject@0.2.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
