[package]
name = "nezuo/spark"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
enumerate = "nezuo/enumerate@0.1.5"
Promise = "evaera/promise@4.0.0"
Subject = "nezuo/subject@0.1.0"
TestEZ = "roblox/testez@0.4.1"