[package]
name = "nezuo/spark"
version = "0.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"

[dev-dependencies]
Midori = "nezuo/midori@0.1.3"
