[package]
name = "nezuo-spark/matter-example"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Matter = "matter-ecs/matter@0.8.4"
Promise = "evaera/promise@4.0.0"